version: '2'
services:
  odoo14:
    build: .
    image: img_odoo14
    container_name: cont_odoo_14-libra
    depends_on:
      - db14
    volumes:
      - "data-odoo-14:/filestore"
      - "./src:/opt/odoo"
    environment:
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_DB_HOST=db
      - ODOO_ADMIN_PASSWORD=randompass
    ports:
      - "8083:8069"
      - "8072:8069"
    restart: always
    #command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc"
    command: "tail -f /dev/null"
    networks: 
      - red-odoo14-db
  db14:
    image: postgres:9.6
    container_name: cont_db_14-libra
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres      
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db-14:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: always
    networks: 
      - red-odoo14-db
      
networks:
   red-odoo14-db:
  
volumes:
  data-odoo-14:
  data-db-14:
